slotify-interesting-facts-section
e-Spirit/fsxa-ui pull request #36
Opened 2021-01-08 10:32 UTC by Dramaturco

refactor: Scoped Slots

Added the possibility of using scoped slots to pass data into the InterestingFactsSection component.

2021-01-08 10:33 UTC, Dramaturco commented
Will do other sections on this branch as well to avoid merge conflicts with the BaseComponent changes.

2021-01-08 15:31 UTC, Dramaturco commented
Added scoped slots to InterestingFacts NewsTeaser and Teaser sections

2021-01-11 09:27 UTC, ninoNato approved these changes
Looks really great! Good job!

2021-01-12 14:54 UTC, tgolbs requested changes
Please add examples for the slots in the InterestingFactsSection and TeaserSection and add the slot descriptions as well.

2021-01-13 14:43 UTC, tgolbs requested changes
Please refactor the Button.tsx as well so that it uses events instead of the callback and fix the comments.

2021-01-13 14:43 UTC, tgolbs commented on src/components/Sections/InterestingFactsSection/index.tsx
> +                {this.$scopedSlots.counters
Please wrap the slot content with the LayoutItem as well. Since this will give some general structure to the section.

2021-01-13 14:43 UTC, tgolbs commented on src/components/Sections/TeaserSection/index.tsx
> +class TeaserSection extends BaseComponent<
Please add a slot "media" as well, which will override the displayed image.

2021-01-13 14:43 UTC, tgolbs commented on src/components/Sections/TeaserSection/index.tsx
> +                <RichText
Please remove the RichText Component and replace it with a simple div. (The RichText-Component is deprecated and will be removed in the next release)

2021-01-13 14:43 UTC, tgolbs commented on src/documentation/examples/TeaserSection.tsx
> +          onClick={() => {
Please change the event to `onButtonClick`. (Although i've told you otherwise before)

2021-01-13 14:43 UTC, tgolbs commented on src/types/sections.d.ts
> +  headline?: string;
Please add some basic comments what kind of slots these will be.

2021-01-15 09:07 UTC, tgolbs approved these changes

2021-01-15 09:14 UTC, merged