Tng 794
e-Spirit/fsxa-ui pull request #57
Opened 2021-01-22 11:05 UTC by rrieger-espirit

In this context, tests for the LineSeparator was created, also some bugfixing in tests

2021-01-25 08:18 UTC, vlapl commented on src/components/ProductListItem/index.tsx
> -          lazy={true}
Das ist, um den Test zu fixen? Ich habe dazu in meinem PR einen anderen Fix, mit dem man nicht auf "lazy" verzichten braucht: https://github.com/e-Spirit/fsxa-ui/pull/54/commits/801590b073693d5ae25259ffeb25cb9ace702a07

2021-01-25 10:16 UTC, dbarczewski requested changes
Great job so far. You only need to make a few small improvements.

2021-01-25 10:16 UTC, dbarczewski commented on src/components/LineSeparator/__tests__/LineSeperator.spec.tsx
> +    const { getByTestId } = render(LineSeperator, {});
Please remove unnecessary empty object.

2021-01-25 10:16 UTC, dbarczewski commented on src/components/LineSeparator/__tests__/LineSeperator.spec.tsx
> +  it("renders responsive", () => {
Please provide a better test message.

2021-01-25 10:16 UTC, dbarczewski commented on src/components/LineSeparator/__tests__/LineSeperator.spec.tsx
> +import { render } from "@testing-library/vue";
Please rename the file to "LineSeparator.spec.ts"

2021-01-25 12:46 UTC, dbarczewski requested changes

2021-01-25 12:46 UTC, dbarczewski commented on src/components/LineSeparator/__tests__/LineSeperator.spec.ts
> +import LineSeperator from "..";
Please check the spelling for the import and the file name.

2021-01-25 12:46 UTC, dbarczewski commented on src/components/LineSeparator/__tests__/LineSeperator.spec.ts
> +import LineSeperator from "..";
And import the component via `./../`

2021-01-26 08:11 UTC, dbarczewski approved these changes
Nice, well done.

2021-01-26 08:27 UTC, merged