Tng 764
e-Spirit/fsxa-ui pull request #8
Opened 2020-10-01 09:19 UTC by rrieger-espirit

in this ticket i added tests for sections. NewsTeaserSections is not finished yet, this will be fixed by another time

2020-10-29 09:48 UTC, tgolbs requested changes

2020-11-11 13:29 UTC, vlapl commented on src/components/Sections/HeaderSection/Breadcrumbs/__tests__/Breadcrumbs.spec.tsx
> +import { render, fireEvent } from "@testing-library/vue";
Hat Robin mit "checks if all items have been rendered and are in the right order" getan.

2020-11-11 13:33 UTC, vlapl commented on src/components/Sections/HeaderSection/Breadcrumbs/__tests__/Breadcrumbs.spec.tsx
> +    expect(spy).toHaveBeenCalled();
Das wird jetzt gemacht mit expect(spy.mock.calls[0][0]).toEqual

2020-11-11 14:16 UTC, vlapl commented on src/components/Sections/HeaderSection/__tests__/HeaderSection.spec.tsx
> +import { render, fireEvent } from "@testing-library/vue";
add test it("correctly consumes the specified background image"...)

2020-11-11 15:18 UTC, vlapl commented on src/components/Sections/TeaserSection/__tests__/TeaserSection.spec.tsx
> +import { fireEvent, render } from "@testing-library/vue";
done

2020-11-11 15:21 UTC, vlapl commented on src/components/Sections/TeaserSection/__tests__/TeaserSection.spec.tsx
> +    const headline = getByTestId("teasersection-headline");
done

2020-11-24 08:54 UTC, tgolbs approved these changes

2020-11-24 11:11 UTC, vlapl approved these changes
Tobi did the review this morning (with me watching). Now I fixed a typo, as agreed upon, and will proceed merging this pr.

2020-11-24 11:16 UTC, merged