Tng 778
e-Spirit/fsxa-ui pull request #9
Opened 2020-10-01 11:17 UTC by rrieger-espirit

in this ticket I created tests for the footer

2020-10-29 09:50 UTC, tgolbs requested changes

2020-10-29 09:50 UTC, tgolbs commented on src/components/Footer/__tests__/Footer.spec.tsx
> +    expect(spy).toHaveBeenCalled();
Please add an expect where you check for the item as well.

2020-10-29 09:50 UTC, tgolbs commented on src/components/Footer/__tests__/Footer.spec.tsx
> +    expect(copyRightTest).toBeTruthy();
Please change test to check for correct text and add tests for the footer-links / logo as well.

2020-11-17 14:17 UTC, ninoNato commented on src/components/Footer/__tests__/Footer.spec.tsx
> +    });
Please use the object initializer shorthand:
`props: { copyright, links, handleClick: spy },`

2020-11-17 14:19 UTC, ninoNato commented on src/components/Footer/__tests__/Footer.spec.tsx
> +        copyright: copyright,
Please use the object initializer shorthand:
`copyright` instead of `copyright: copyright`

2020-11-27 10:34 UTC, tgolbs requested changes

2020-11-27 10:34 UTC, tgolbs commented on src/components/Footer/__tests__/Footer.spec.tsx
> +        copyright: copyright,
Please use shorthand.

2020-11-27 10:36 UTC, tgolbs approved these changes

2020-11-27 10:36 UTC, merged